### ISSUE TITLE
Migrate from Travis to Github Actions

### ISSUE THREAD

**Issue by latin-panda** [medic/pyxform#7]
**Description**
Travis seems to be winding down the free tier with very long queue times, so we're migrating the repositories to use Github Actions.

Please replace Travis with Github Actions.

**Comment by Omswastik-11** [comment]
Hi @latin-panda is this issue still open? Can I contribute?

**Comment by jkuester** [comment]
There is no way to move to main-line pyxform (and off this fork) without requiring non-passive changes to some CHT xlsxforms.  So, in that sense, we should consider this fork of pyxform to be "currently maintained".  Even though we have not needed to make changes out here in years, we still might (and very much want to https://github.com/medic/pyxform/issues/8).  

With that in mind, yes, I think it would be valuable to have a basic GitHub Action setup to build this repo. Probably just needs to install the package and try to run the `setup.py` like the [existing travis config](https://github.com/medic/pyxform/blob/medic-conf-1.5/.travis.yml).  Should be okay to just target the latest Python 3.x.

Things could get a bit tricky here since it has been a long time since anyone has ever tried to build this, but @Omswastik-11 feel free to give it a go!

**Comment by Omswastik-11** [comment]
Thanks @jkuester for assigning me . I will try my best!!

**Comment by Omswastik-11** [comment]
Hi @jkuester , @mrjones-plip , @latin-panda !!

which branch should I work on to make changes ?

**Comment by Omswastik-11** [comment]
It seems that Latest` Pyxform` is supported for python version 3.12, 3.11, 3.10. but according to `.travis.yml` file it supported for 2.7, 3.4, 3.5 . Do I need to change some thing else in the code base ? 

I made a `.github\workflow` directory added a sample `main.yml` file .

` name: CI

on:
  push:
    branches: [ medic-conf-1.5 ]
  pull_request:
    branches: [ medic-conf-1.5]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.4, 3.5]
        env:
          - RUNTESTS=nosetests
          - RUNTESTS='nosetests --tests pyxform/tests_v1/'
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.pip
      - name: Run tests
        env:
          RUNTESTS: ${{ matrix.env.RUNTESTS }}
        run: python setup.py $RUNTESTS `


I have few doubts.. 

1.  Should I add these actions on push or pull or any thing else ?
2. On which branch should I work on ?
3. Should work on same python version or should try 3.10,3.11,3.12 ?

**Comment by jkuester** [comment]
> On which branch I should work on ?

This is a good question. The branching strategy for this repo is... broken?  Regardless, you should base you changes on `medic-conf-1.17`. That is the code being used currently in production.

> It seems that Latest Pyxform is supported for python version 3.12, 3.11, 3.10. but according to .travis.yml file it supported for 2.7, 3.4, 3.5 .

At this point we only care about supporting Python `3.x`.  So, if it is possible it would be great to test across Python 3.9, 3.10, 3.11, 3.12, and 3.13. 👍 

> Do I need to change some thing else in the code base ?

Ideally we would not need any other changes to the code (assuming the build still works...).

> Should I add these actions on push or pull or any thing else ?

Lets keep it simple for now and just trigger the build `on: [push, pull_request]`

**Comment by Omswastik-11** [comment]
@jkuester 
It seems the `requirement.txt` file
 `nose==1.3.7 
FormEncode==1.3 
modilabs-python-utils==0.1.5 
xlrd==1.0.0 
unittest2==1.1.0 
unicodecsv==0.14.1`

It requires less than 3.6 python versions but It is not supported in the github Ubuntu 24.04 / 22.04 runners . I tried using 3.12.0 version but it is raising some errors .



 `Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [[20](https://github.com/Omswastik-11/pyxform/actions/runs/14801594719/job/41561389589#step:4:21) lines of output]
      Traceback (most recent call last):
        File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 389, in <module>
          main()
        File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 373, in main
          json_out["return_val"] = hook(**hook_input["kwargs"])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 143, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-gfv6g5r4/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 331, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-gfv6g5r4/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line [30](https://github.com/Omswastik-11/pyxform/actions/runs/14801594719/job/41561389589#step:4:31)1, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-gfv6g5r4/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 512, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-gfv6g5r4/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line [31](https://github.com/Omswastik-11/pyxform/actions/runs/14801594719/job/41561389589#step:4:32)7, in run_setup
          exec(code, locals())
        File "<string>", line 15, in <module>
      ImportError: Python version not supported
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.`

![Image](https://github.com/user-attachments/assets/ec054840-37ab-4f3f-89b0-e32efcbb4058)

**Comment by Omswastik-11** [comment]
What Should i do next ? Should I try various combinations of Ubuntu and python version ? Or I should try with some other runners like macOS ,Windows ? There can be one way to entirely update the dependencies..

**Comment by jkuester** [comment]
> It requires less than 3.6 python versions but It is not supported in the github Ubuntu 24.04 / 22.04 runners (20.04 is removed).

Yeah, this was the kind of thing I was afraid of... 😞  Lets scope our efforts to getting this to build on the `ubuntu-24.04` runner; whatever it takes to make that happen.  So, we can update the `requirement.txt` to target the Python versions supported by Ubuntu 24.04 and update any other dependency versions as needed. 👍 

> By the way I already forked the default branch . Do I need to change it to medic-conf-1.17 ?

Looking at the commit history, there should not be too much of a difference between `medic-conf-1.5` and `medic-conf-1.17`.  I expect you are find developing on top of `medic-conf-1.5`, but your PR will need to target `medic-conf-1.17` as the base.

**Comment by Omswastik-11** [comment]
Hi @jkuester !!
it seems `python version 3.9 `is suported on latest ubuntu runners I have updated the dependencies but it seems this requires a lot of changes in test scripts because many module has been updated I have updated some but it quite large in number . 

For example :
```

======================================================================
ERROR: test_xls_to_csv (pyxform.tests.file_utils_test.BackendUtilsTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/pyxform/pyxform/pyxform/tests/file_utils_test.py", line 10, in test_xls_to_csv
    converted_xls = convert_file_to_csv_string(specify_other_xls)
  File "/home/runner/work/pyxform/pyxform/pyxform/xls2json_backends.py", line 338, in convert_file_to_csv_string
    writer.writerow([sheet_name])
TypeError: a bytes-like object is required, not 'str'

======================================================================
ERROR: Failure: ModuleNotFoundError (No module named 'unittest2')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.22/x64/lib/python3.9/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/opt/hostedtoolcache/Python/3.9.22/x64/lib/python3.9/site-packages/nose/loader.py", line 417, in loadTestsFromName
    module = self.importer.importFromPath(
  File "/opt/hostedtoolcache/Python/3.9.22/x64/lib/python3.9/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/opt/hostedtoolcache/Python/3.9.22/x64/lib/python3.9/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/opt/hostedtoolcache/Python/3.9.22/x64/lib/python3.9/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/opt/hostedtoolcache/Python/3.9.22/x64/lib/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/runner/work/pyxform/pyxform/pyxform/tests/new_cascading_select_test.py", line 1, in <module>
    import unittest2 as unittest
ModuleNotFoundError: No module named 'unittest2'
```

I am currently working on it would it be fine should I proceed with this ?

**Comment by jkuester** [comment]
>  it seems this requires a lot of changes in test scripts because many module has been updated I have updated some but it quite large in number .

🤔 Under normal circumstances, I would say yes we should try to update the tests.  HOWEVER, since we plan to address https://github.com/medic/pyxform/issues/8 immanently, and the changes for that ticket should involve pulling in all the new test changes from the upstream repository, then I think we should not spend a whole lot of effort getting our existing tests working.  

For this ticket, lets just avoid running the tests as part of the CI build. (Or maybe just run a small subset that actually work without much effort?)  I think we should avoid making any sweeping changes to the code-base here as they are likely to not be relevant after #8.

**Comment by Omswastik-11** [comment]
Hi @jkuester !! 
I raised a PR I have updated the CI `build.yml` file as you mentioned . It just builds and install some dependencies and avoided running the tests .

**Comment by jkuester** [comment]
https://github.com/medic/pyxform/pull/14
